### ISSUE TITLE
Artifactory Generic Download - Script error on TFS 2018u3

### ISSUE THREAD

**Issue by dnperfors** [jfrog/artifactory-vsts-extension#74]
Hi,

I just tried to use the Artifactory Generic Download task in our build, but I get some javascript errors when the task is run. I used both version 1.* and version 2.* of the task.

Error for version 1.*:
```
2019-05-13T09:09:52.6424980Z ==============================================================================
2019-05-13T09:09:52.6447830Z Task         : Artifactory Generic Download
2019-05-13T09:09:52.6480710Z Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2019-05-13T09:09:52.6513730Z Version      : 1.5.0
2019-05-13T09:09:52.6538660Z Author       : JFrog
2019-05-13T09:09:52.6563150Z Help         : 
2019-05-13T09:09:52.6596700Z ==============================================================================
2019-05-13T09:09:53.1299200Z /vsts/agent/_work/_tasks/ArtifactoryGenericDownload_07fc5c20-6772-11e5-abde-6901d3c00755/1.5.0/downloadArtifacts.js:10
2019-05-13T09:09:53.1333700Z     let buildDefinition = tl.getVariable('Build.DefinitionName');
2019-05-13T09:09:53.1360380Z     ^^^
2019-05-13T09:09:53.1369820Z 
2019-05-13T09:09:53.1393740Z SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2019-05-13T09:09:53.1420480Z     at exports.runInThisContext (vm.js:53:16)
2019-05-13T09:09:53.1442510Z     at Module._compile (module.js:387:25)
2019-05-13T09:09:53.1461970Z     at Object.Module._extensions..js (module.js:422:10)
2019-05-13T09:09:53.1482440Z     at Module.load (module.js:357:32)
2019-05-13T09:09:53.1503090Z     at Function.Module._load (module.js:314:12)
2019-05-13T09:09:53.1526550Z     at Function.Module.runMain (module.js:447:10)
2019-05-13T09:09:53.1545690Z     at startup (node.js:146:18)
2019-05-13T09:09:53.1566350Z     at node.js:404:3
```

Version 2.*:
```
2019-05-13T09:08:40.8778690Z ==============================================================================
2019-05-13T09:08:40.8800730Z Task         : Artifactory Generic Download
2019-05-13T09:08:40.8825560Z Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2019-05-13T09:08:40.8853230Z Version      : 2.5.0
2019-05-13T09:08:40.8874320Z Author       : JFrog
2019-05-13T09:08:40.8896700Z Help         : 
2019-05-13T09:08:40.8915820Z ==============================================================================
2019-05-13T09:08:41.3244970Z /vsts/agent/_work/_tasks/ArtifactoryGenericDownload_07fc5c20-6772-11e5-abde-6901d3c00755/2.5.0/downloadArtifacts.js:10
2019-05-13T09:08:41.3276200Z     let workDir = tl.getVariable('System.DefaultWorkingDirectory');
2019-05-13T09:08:41.3298620Z     ^^^
2019-05-13T09:08:41.3308060Z 
2019-05-13T09:08:41.3337300Z SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2019-05-13T09:08:41.3362320Z     at exports.runInThisContext (vm.js:53:16)
2019-05-13T09:08:41.3381180Z     at Module._compile (module.js:387:25)
2019-05-13T09:08:41.3402900Z     at Object.Module._extensions..js (module.js:422:10)
2019-05-13T09:08:41.3424780Z     at Module.load (module.js:357:32)
2019-05-13T09:08:41.3445570Z     at Function.Module._load (module.js:314:12)
2019-05-13T09:08:41.3464840Z     at Function.Module.runMain (module.js:447:10)
2019-05-13T09:08:41.3486760Z     at startup (node.js:146:18)
2019-05-13T09:08:41.3505530Z     at node.js:404:3
```

Possible relevant information about the environment I am using:

- TFS 2018 update 3: Version 16.131.28106.2
- Agent version: 2.116.1
- Agent os: Linux
- Node.JS version: v8.11.2

Any idea what could have caused this issue and how it can be solved?

**Comment by dnperfors** [comment]
Actually, I get the same error when trying to use the upload task... Any update on this issue?

**Comment by eyalbe4** [comment]
@dnperfors - sorry for the late response!

This error message - 
**SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode**  
indicates that the NodeJS version installed on the build agent is too old. You mentioned that you're using  v8.11.2, which  should be okay...
Are you sure that the specific build agent which fails with this error doesn't have an older NodeJS version?
You can check this by running **node -v** from the build agent's terminal.

**Comment by dnperfors** [comment]
Hi @eyalbe4,

Yes v8.11.2 is the actual node version...

**Comment by eyalbe4** [comment]
@dnperfors,
A college of mine encountered the same issue, and suggested replacing the node executable on the build agent, exactly as described [here](https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension#AzureDevOpsandTFSArtifactoryExtension-UsingTFS2015)
Please let me know if this resolves the issue.

**Comment by eyalbe4** [comment]
@dnperfors,
P|lease let us know if you'd like to discuss this further. Closing this issue for now.
